spring:
#  激活local配置
  profiles:
    active: local
  application:
    name: campusClassroomReservationSystem
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yaml
    disable-swagger-default-url: true
server:
  port: 8080